language: python

sudo: required

matrix:
    include:
        # Current production
        - python: '2.7'
          env: ELASTICSEARCH_VERSION=1.4.4
        - python: "3.5"
          env: ELASTICSEARCH_VERSION=1.4.4
        # Latest in 1.X line (as of 2016-02-10). For speed, just run future ES version with latest Python
        - python: '3.5'
          env: ELASTICSEARCH_VERSION=1.7.5
cache:
  directories:
    - $HOME/.cache/pip
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  # Use same ES version as in production (also the Travis "elasticsearch" service setting fails to start)
  - travis_retry curl -OL https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo service elasticsearch start
install:
  - travis_retry pip install -e .
  - travis_retry pip install "file://$(pwd)#egg=django-bulbs[dev]"
before_script:
  - psql -c "create database bulbs_test;" -U postgres
  - psql -c "create user bulbs WITH superuser PASSWORD 'testing';" -U postgres
  # Wait for ES startup
  - until curl http://localhost:9200/; do sleep 1; done
script:
  - py.test --cov bulbs --cov-report term-missing
  - npm test
  - scripts/lint
after_success:
  - coveralls
