language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

# hand-crafted matrix of
# python: 2.7, 3.4, 3.5
# elasticsearch: 1.4.4 (prod), 1.4.5 (next), 1.7.5 (future)
matrix:
  include:
    - python: '2.7'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.4
          packages:
            - elasticsearch
    - python: '2.7'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.5
          packages:
            - elasticsearch
    - python: '2.7'
      addons:
        apt:
          sources:
            - elasticsearch-1.7.5
          packages:
            - elasticsearch
    - python: '3.4'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.4
          packages:
            - elasticsearch
    - python: '3.4'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.5
          packages:
            - elasticsearch
    - python: '3.4'
      addons:
        apt:
          sources:
            - elasticsearch-1.7.5
          packages:
            - elasticsearch
    - python: '3.5'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.4
          packages:
            - elasticsearch
    - python: '3.5'
      addons:
        apt:
          sources:
            - elasticsearch-1.4.5
          packages:
            - elasticsearch
    - python: '3.5'
      addons:
        apt:
          sources:
            - elasticsearch-1.7.5
          packages:
            - elasticsearch
services:
  - postgresql
  - elasticsearch

before_install:
  - sleep 10
install:
  - travis_retry pip install -e .
  - travis_retry pip install "file://$(pwd)#egg=django-bulbs[dev]"
before_script:
  - psql -c 'create database bulbs;' -U postgres
  # Travis/ES troubleshooting
  - elasticsearch -v
  # Wait for ES startup
  - until curl http://localhost:9200/; do sleep 1; done
script:
  - py.test --cov bulbs --cov-report term-missing
after_success:
  - coveralls
