language: python
sudo: required
python:
  - '2.7'
  - '3.4'
  - '3.5'
env:
    - ELASTICSEARCH_VERSION=1.4.4
    #- ELASTICSEARCH_VERSION=1.4.5
    # TODO: MORE?
install:
  # Use same ES version as in production (also the Travis "elasticsearch" service setting fails to start)
  - travis_retry curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ELASTICSEARCH_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ELASTICSEARCH_VERSION.deb
  - sudo service elasticsearch start
  - travis_retry pip install -e .
  - travis_retry pip install "file://$(pwd)#egg=django-bulbs[dev]"
services:
  - postgresql
  #- elasticsearch
before_script:
  - psql -c 'create database bulbs;' -U postgres
  - until curl http://localhost:9200/; do sleep 1; done
script: py.test --cov bulbs --cov-report term-missing
after_success:
  - coveralls
sudo: false
