language: python
python:
  - '2.7'
install:
  - travis_retry pip install -e .
  - travis_retry pip install "file://$(pwd)#egg=django-bulbs[dev]"
services:
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create database bulbs;' -U postgres
script: py.test --cov bulbs --cov-report term-missing
after_success:
  - coveralls