language: python
python:
  - "2.7"
cache:
  directories:
  - pipcache
install: "PIP_DOWNLOAD_CACHE=./pipcache pip install -r requirements-dev.txt"
services:
  - elasticsearch
  - postgresql
before_script:
  - psql -c 'create database bulbs;' -U postgres
script: python runtests.py