web:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: example.settings
  # FROM https://github.com/unbit/uwsgi-docker
  # in bridged mode the class B network is allocated, so we can simply bind to the first address starting with 172
  # so we use the very handy .* trick
  # NOTE: If uWSGI "--python-autoreload" doesn't work / is too slow, could try Django handler: http://serverfault.com/a/642024
  stdin_open: true
  volumes:
    - .:/webapp
  external_links:
    - onionservices_elasticsearch_1:elasticsearch
    - onionservices_fastrouter_1:fastrouter
    - onionservices_memcached_1:memcached
    - onionservices_postgres_1:postgres
    - onionservices_rabbitmq_1:rabbitmq
    - onionservices_fastrouter_1:tunic.local